// Port of numpy's `random_binomial` / `random_multinomial` (numpy's
// `distributions.c`), the last piece of `np.random.Generator` that hoops-sim
// consumes and this repo hadn't ported yet.
//
// 🔴 SECOND IMPLEMENTATION WARNING, same as engine.ts. hoops-sim's
// `hoops.boxscore` allocates every integer box-score stat with
// `rng.stream(...).multinomial(total, shares)`. Reproducing a box score here
// means reproducing that draw exactly — which means porting the conditional-
// binomial decomposition AND both binomial samplers underneath it, branch for
// branch, because they consume different numbers of uniforms.
//
// The check is scripts/check-hoops-multinomial.ts, asserting against
// hoops-data/hoops_multinomial_cases.json — cases generated by running the
// REAL numpy through hoops-sim's own `hoops.rng.stream`, not by this file
// agreeing with itself. Regenerate with:
//
//     cd ~/Code/hoops-sim && uv run python \
//       ~/Code/keith-hub/scripts/gen_multinomial_cases.py
//
// Mechanics that are easy to get wrong, and are each pinned by a case:
//
//   • Multinomial is a chain of binomials on the CONDITIONAL probability
//     `pix[j] / remaining_p`, not on `pix[j]`. It stops early the moment the
//     remaining count hits zero — so a low-share player late in the list can
//     consume no randomness at all.
//   • `random_binomial` flips to the complement when p > 0.5 and subtracts,
//     so the branch threshold (`p*n <= 30`) is evaluated on the FLIPPED p.
//     Getting this backwards picks the wrong sampler and desyncs the stream.
//   • BTPE and inversion consume different draw counts per variate, and both
//     can loop. There is no "just take one uniform" shortcut that stays in
//     sync.
//   • numpy caches the per-(n,p) setup on the Generator's binomial struct and
//     REUSES it across the categories of one multinomial call. The cache is
//     semantically transparent (same n,p ⇒ same derived values), so this port
//     recomputes instead of caching — a deliberate simplification that cannot
//     change a draw.

import type { PhiloxGenerator } from "./philox.ts";

const MIN = Math.min;

/**
 * numpy's `random_binomial_inversion` — the small-mean path (`p*n <= 30`).
 * Walks the PMF from zero, restarting with a fresh uniform if the walk runs
 * past `bound`.
 */
function binomialInversion(gen: PhiloxGenerator, n: number, p: number): number {
  const q = 1.0 - p;
  const qn = Math.exp(n * Math.log(q));
  const np = n * p;
  const bound = MIN(n, np + 10.0 * Math.sqrt(np * q + 1));

  let x = 0;
  let px = qn;
  let u = gen.nextDouble();
  while (u > px) {
    x++;
    if (x > bound) {
      x = 0;
      px = qn;
      u = gen.nextDouble();
      continue;
    }
    u -= px;
    px = ((n - x + 1) * p * px) / (x * q);
  }
  return x;
}

/**
 * numpy's `random_binomial_btpe` — Kachitvichyanukul & Schmeiser's BTPE, the
 * large-mean path (`p*n > 30`). Kept in the original's goto-step shape (a
 * labelled loop with an explicit step variable) rather than restructured into
 * idiomatic control flow: every `goto Step10` is a REJECTION that redraws two
 * uniforms, and flattening the steps into nested conditionals is exactly how
 * a port silently loses one of them.
 *
 * `p` is always <= 0.5 here — `randomBinomial` below flips first — so the
 * original's own trailing `if (p > 0.5) y = n - y` is unreachable and is
 * omitted rather than ported as dead code.
 */
function binomialBtpe(gen: PhiloxGenerator, n: number, p: number): number {
  const r = MIN(p, 1.0 - p);
  const q = 1.0 - r;
  const fm = n * r + r;
  const m = Math.floor(fm);
  const p1 = Math.floor(2.195 * Math.sqrt(n * r * q) - 4.6 * q) + 0.5;
  const xm = m + 0.5;
  const xl = xm - p1;
  const xr = xm + p1;
  const c = 0.134 + 20.5 / (15.3 + m);
  let a = (fm - xl) / (fm - xl * r);
  const laml = a * (1.0 + a / 2.0);
  a = (xr - fm) / (xr * q);
  const lamr = a * (1.0 + a / 2.0);
  const p2 = p1 * (1.0 + 2.0 * c);
  const p3 = p2 + c / laml;
  const p4 = p3 + c / lamr;

  const nrq = n * r * q;

  let u = 0;
  let v = 0;
  let y = 0;
  let step = 10;

  for (;;) {
    if (step === 10) {
      u = gen.nextDouble() * p4;
      v = gen.nextDouble();
      if (u > p1) {
        step = 20;
        continue;
      }
      y = Math.floor(xm - p1 * v + u);
      return y;
    }

    if (step === 20) {
      if (u > p2) {
        step = 30;
        continue;
      }
      const x = xl + (u - p1) / c;
      v = v * c + 1.0 - Math.abs(m - x + 0.5) / p1;
      if (v > 1.0) {
        step = 10;
        continue;
      }
      y = Math.floor(x);
      step = 50;
      continue;
    }

    if (step === 30) {
      if (u > p3) {
        step = 40;
        continue;
      }
      y = Math.floor(xl + Math.log(v) / laml);
      // v === 0 would make the cast above undefined in C; numpy rejects it.
      if (y < 0 || v === 0.0) {
        step = 10;
        continue;
      }
      v = v * (u - p2) * laml;
      step = 50;
      continue;
    }

    if (step === 40) {
      y = Math.floor(xr - Math.log(v) / lamr);
      if (y > n || v === 0.0) {
        step = 10;
        continue;
      }
      v = v * (u - p3) * lamr;
      step = 50;
      continue;
    }

    // Step 50 — the squeeze, then the exact / asymptotic acceptance test.
    const k = Math.abs(y - m);
    if (k > 20 && k < nrq / 2.0 - 1) {
      // Step 52: the Stirling-series acceptance test for a far-out y.
      const rho = (k / nrq) * ((k * (k / 3.0 + 0.625) + 0.16666666666666666) / nrq + 0.5);
      const t = (-k * k) / (2 * nrq);
      const A = Math.log(v);
      if (A < t - rho) return y;
      if (A > t + rho) {
        step = 10;
        continue;
      }

      const x1 = y + 1;
      const f1 = m + 1;
      const z = n + 1 - m;
      const w = n - y + 1;
      const x2 = x1 * x1;
      const f2 = f1 * f1;
      const z2 = z * z;
      const w2 = w * w;
      if (
        A >
        xm * Math.log(f1 / x1) +
          (n - m + 0.5) * Math.log(z / w) +
          (y - m) * Math.log((w * r) / (x1 * q)) +
          (13680.0 - (462.0 - (132.0 - (99.0 - 140.0 / f2) / f2) / f2) / f2) / f1 / 166320.0 +
          (13680.0 - (462.0 - (132.0 - (99.0 - 140.0 / z2) / z2) / z2) / z2) / z / 166320.0 +
          (13680.0 - (462.0 - (132.0 - (99.0 - 140.0 / x2) / x2) / x2) / x2) / x1 / 166320.0 +
          (13680.0 - (462.0 - (132.0 - (99.0 - 140.0 / w2) / w2) / w2) / w2) / w / 166320.0
      ) {
        step = 10;
        continue;
      }
      return y;
    }

    // Exact ratio-of-PMFs test for a y close to the mode.
    const s = r / q;
    const aa = s * (n + 1);
    let F = 1.0;
    if (m < y) {
      for (let i = m + 1; i <= y; i++) F *= aa / i - s;
    } else if (m > y) {
      for (let i = y + 1; i <= m; i++) F /= aa / i - s;
    }
    if (v > F) {
      step = 10;
      continue;
    }
    return y;
  }
}

/**
 * numpy's `random_binomial`. The p > 0.5 flip is load-bearing twice over: it
 * decides which sampler runs, and both samplers are only valid on the smaller
 * tail.
 */
export function randomBinomial(gen: PhiloxGenerator, p: number, n: number): number {
  if (n === 0 || p === 0.0) return 0;
  if (p <= 0.5) {
    return p * n <= 30.0 ? binomialInversion(gen, n, p) : binomialBtpe(gen, n, p);
  }
  const q = 1.0 - p;
  return q * n <= 30.0 ? n - binomialInversion(gen, n, q) : n - binomialBtpe(gen, n, q);
}

/**
 * numpy's `random_multinomial`, i.e. `Generator.multinomial(n, pvals)` for a
 * 1-D `pvals`. Conditional-binomial decomposition: category j is binomial on
 * `pix[j] / remaining_p` out of whatever count is left, and the LAST category
 * absorbs the remainder without a draw.
 *
 * The early `break` when the count is exhausted is not an optimisation — it
 * is part of the stream contract. Categories after it consume nothing.
 */
export function randomMultinomial(
  gen: PhiloxGenerator,
  n: number,
  pvals: ArrayLike<number>,
): Int32Array {
  const d = pvals.length;
  const out = new Int32Array(d);
  if (d === 0) return out;

  let remainingP = 1.0;
  let dn = n;
  for (let j = 0; j < d - 1; j++) {
    out[j] = randomBinomial(gen, pvals[j] / remainingP, dn);
    dn -= out[j];
    if (dn <= 0) break;
    remainingP -= pvals[j];
  }
  if (dn > 0) out[d - 1] = dn;
  return out;
}
