// AUTO-GENERATED by scripts/generate-comics-data.mjs.
// Source: ~/Code/hickman-xmen/{lookup,applinks}.json
// Re-run the script if the underlying reading order changes.

export interface ComicIssue {
  id: string;
  title: string;
  digitalBookId: string;
  marvelIssueId: string;
  slug: string;
}

export interface Storyline {
  slug: string;
  title: string;
  description?: string;
  issues: ComicIssue[];
}

export const STORYLINES: Storyline[] = [
  {
    slug: "hickman-x-men",
    title: "Jonathan Hickman's X-Men",
    description:
      "House of X / Powers of X through the X of Swords crossover. 150 issues.",
    issues: [
          {
                "id": "51975",
                "title": "House of X #1",
                "digitalBookId": "51975",
                "marvelIssueId": "72984",
                "slug": "house_of_x_2019_1"
          },
          {
                "id": "51997",
                "title": "Powers of X #1",
                "digitalBookId": "51997",
                "marvelIssueId": "72991",
                "slug": "powers_of_x_2019_1"
          },
          {
                "id": "52316",
                "title": "House of X #2",
                "digitalBookId": "52316",
                "marvelIssueId": "72985",
                "slug": "house_of_x_2019_2"
          },
          {
                "id": "52353",
                "title": "Powers of X #2",
                "digitalBookId": "52353",
                "marvelIssueId": "72992",
                "slug": "powers_of_x_2019_2"
          },
          {
                "id": "52382",
                "title": "Powers of X #3",
                "digitalBookId": "52382",
                "marvelIssueId": "72993",
                "slug": "powers_of_x_2019_3"
          },
          {
                "id": "52403",
                "title": "House of X #3",
                "digitalBookId": "52403",
                "marvelIssueId": "72986",
                "slug": "house_of_x_2019_3"
          },
          {
                "id": "52491",
                "title": "House of X #4",
                "digitalBookId": "52491",
                "marvelIssueId": "72987",
                "slug": "house_of_x_2019_4"
          },
          {
                "id": "52319",
                "title": "Marvel Comics #1000",
                "digitalBookId": "52319",
                "marvelIssueId": "75125",
                "slug": "marvel_comics_2019_1000"
          },
          {
                "id": "52537",
                "title": "Powers of X #4",
                "digitalBookId": "52537",
                "marvelIssueId": "72994",
                "slug": "powers_of_x_2019_4"
          },
          {
                "id": "52492",
                "title": "House of X #5",
                "digitalBookId": "52492",
                "marvelIssueId": "72988",
                "slug": "house_of_x_2019_5"
          },
          {
                "id": "52538",
                "title": "Powers of X #5",
                "digitalBookId": "52538",
                "marvelIssueId": "72995",
                "slug": "powers_of_x_2019_5"
          },
          {
                "id": "52801",
                "title": "House of X #6",
                "digitalBookId": "52801",
                "marvelIssueId": "72989",
                "slug": "house_of_x_2019_6"
          },
          {
                "id": "52701",
                "title": "Powers of X #6",
                "digitalBookId": "52701",
                "marvelIssueId": "72996",
                "slug": "powers_of_x_2019_6"
          },
          {
                "id": "52818",
                "title": "X-Men (2019) #1",
                "digitalBookId": "52818",
                "marvelIssueId": "76803",
                "slug": "x-men_2019_1"
          },
          {
                "id": "52697",
                "title": "Marauders (2019) #1",
                "digitalBookId": "52697",
                "marvelIssueId": "76750",
                "slug": "marauders_2019_1"
          },
          {
                "id": "52787",
                "title": "Excalibur (2019) #1",
                "digitalBookId": "52787",
                "marvelIssueId": "76729",
                "slug": "excalibur_2019_1"
          },
          {
                "id": "53011",
                "title": "New Mutants (2019) #1",
                "digitalBookId": "53011",
                "marvelIssueId": "76757",
                "slug": "new_mutants_2019_1"
          },
          {
                "id": "53038",
                "title": "X-Force (2019) #1",
                "digitalBookId": "53038",
                "marvelIssueId": "76789",
                "slug": "x-force_2019_1"
          },
          {
                "id": "52984",
                "title": "Fallen Angels (2019) #1",
                "digitalBookId": "52984",
                "marvelIssueId": "76742",
                "slug": "fallen_angels_2019_1"
          },
          {
                "id": "53040",
                "title": "X-Men (2019) #2",
                "digitalBookId": "53040",
                "marvelIssueId": "76804",
                "slug": "x-men_2019_2"
          },
          {
                "id": "53006",
                "title": "Marauders (2019) #2",
                "digitalBookId": "53006",
                "marvelIssueId": "76751",
                "slug": "marauders_2019_2"
          },
          {
                "id": "52983",
                "title": "Excalibur (2019) #2",
                "digitalBookId": "52983",
                "marvelIssueId": "76730",
                "slug": "excalibur_2019_2"
          },
          {
                "id": "53012",
                "title": "New Mutants (2019) #2",
                "digitalBookId": "53012",
                "marvelIssueId": "76758",
                "slug": "new_mutants_2019_2"
          },
          {
                "id": "53039",
                "title": "X-Force (2019) #2",
                "digitalBookId": "53039",
                "marvelIssueId": "76790",
                "slug": "x-force_2019_2"
          },
          {
                "id": "52985",
                "title": "Fallen Angels (2019) #2",
                "digitalBookId": "52985",
                "marvelIssueId": "76743",
                "slug": "fallen_angels_2019_2"
          },
          {
                "id": "53309",
                "title": "X-Men (2019) #3",
                "digitalBookId": "53309",
                "marvelIssueId": "76805",
                "slug": "x-men_2019_3"
          },
          {
                "id": "53267",
                "title": "Marauders (2019) #3",
                "digitalBookId": "53267",
                "marvelIssueId": "76752",
                "slug": "marauders_2019_3"
          },
          {
                "id": "53233",
                "title": "Excalibur (2019) #3",
                "digitalBookId": "53233",
                "marvelIssueId": "76731",
                "slug": "excalibur_2019_3"
          },
          {
                "id": "53275",
                "title": "New Mutants (2019) #3",
                "digitalBookId": "53275",
                "marvelIssueId": "76759",
                "slug": "new_mutants_2019_3"
          },
          {
                "id": "53307",
                "title": "X-Force (2019) #3",
                "digitalBookId": "53307",
                "marvelIssueId": "76791",
                "slug": "x-force_2019_3"
          },
          {
                "id": "53241",
                "title": "Fallen Angels (2019) #3",
                "digitalBookId": "53241",
                "marvelIssueId": "76744",
                "slug": "fallen_angels_2019_3"
          },
          {
                "id": "53268",
                "title": "Marauders (2019) #4",
                "digitalBookId": "53268",
                "marvelIssueId": "76753",
                "slug": "marauders_2019_4"
          },
          {
                "id": "53308",
                "title": "X-Force (2019) #4",
                "digitalBookId": "53308",
                "marvelIssueId": "76792",
                "slug": "x-force_2019_4"
          },
          {
                "id": "53274",
                "title": "New Mutants (2019) #4",
                "digitalBookId": "53274",
                "marvelIssueId": "76760",
                "slug": "new_mutants_2019_4"
          },
          {
                "id": "53239",
                "title": "Excalibur (2019) #4",
                "digitalBookId": "53239",
                "marvelIssueId": "76732",
                "slug": "excalibur_2019_4"
          },
          {
                "id": "53245",
                "title": "Fallen Angels (2019) #4",
                "digitalBookId": "53245",
                "marvelIssueId": "76745",
                "slug": "fallen_angels_2019_4"
          },
          {
                "id": "53263",
                "title": "Incoming #1",
                "digitalBookId": "53263",
                "marvelIssueId": "76984",
                "slug": "incoming_2019_1"
          },
          {
                "id": "53258",
                "title": "Gwenpool Strikes Back #5",
                "digitalBookId": "53258",
                "marvelIssueId": "76055",
                "slug": "gwenpool_strikes_back_2019_5"
          },
          {
                "id": "53310",
                "title": "X-Men (2019) #4",
                "digitalBookId": "53310",
                "marvelIssueId": "76806",
                "slug": "x-men_2019_4"
          },
          {
                "id": "53566",
                "title": "Marauders (2019) #5",
                "digitalBookId": "53566",
                "marvelIssueId": "76754",
                "slug": "marauders_2019_5"
          },
          {
                "id": "53576",
                "title": "New Mutants (2019) #5",
                "digitalBookId": "53576",
                "marvelIssueId": "76761",
                "slug": "new_mutants_2019_5"
          },
          {
                "id": "52710",
                "title": "X-Force (2019) #5",
                "digitalBookId": "52710",
                "marvelIssueId": "76793",
                "slug": "x-force_2019_5"
          },
          {
                "id": "53548",
                "title": "Excalibur (2019) #5",
                "digitalBookId": "53548",
                "marvelIssueId": "76733",
                "slug": "excalibur_2019_5"
          },
          {
                "id": "53550",
                "title": "Fallen Angels (2019) #5",
                "digitalBookId": "53550",
                "marvelIssueId": "76746",
                "slug": "fallen_angels_2019_5"
          },
          {
                "id": "53549",
                "title": "Excalibur (2019) #6",
                "digitalBookId": "53549",
                "marvelIssueId": "76734",
                "slug": "excalibur_2019_6"
          },
          {
                "id": "53991",
                "title": "Marvel's Voices #1",
                "digitalBookId": "53991",
                "marvelIssueId": "84188",
                "slug": "marvels_voices_2020_1"
          },
          {
                "id": "54085",
                "title": "X-Men/Fantastic Four (2020) #1",
                "digitalBookId": "54085",
                "marvelIssueId": "77993",
                "slug": "x-menfantastic_four_2020_1"
          },
          {
                "id": "54086",
                "title": "X-Men/Fantastic Four (2020) #2",
                "digitalBookId": "54086",
                "marvelIssueId": "77995",
                "slug": "x-menfantastic_four_2020_2"
          },
          {
                "id": "54359",
                "title": "X-Men/Fantastic Four (2020) #3",
                "digitalBookId": "54359",
                "marvelIssueId": "77996",
                "slug": "x-menfantastic_four_2020_3"
          },
          {
                "id": "54671",
                "title": "X-Men/Fantastic Four (2020) #4",
                "digitalBookId": "54671",
                "marvelIssueId": "77997",
                "slug": "x-menfantastic_four_2020_4"
          },
          {
                "id": "54079",
                "title": "Wolverine (2020) #1",
                "digitalBookId": "54079",
                "marvelIssueId": "78724",
                "slug": "wolverine_2020_1"
          },
          {
                "id": "53567",
                "title": "Marauders (2019) #6",
                "digitalBookId": "53567",
                "marvelIssueId": "76755",
                "slug": "marauders_2019_6"
          },
          {
                "id": "53551",
                "title": "Fallen Angels (2019) #6",
                "digitalBookId": "53551",
                "marvelIssueId": "76747",
                "slug": "fallen_angels_2019_6"
          },
          {
                "id": "53577",
                "title": "New Mutants (2019) #6",
                "digitalBookId": "53577",
                "marvelIssueId": "76762",
                "slug": "new_mutants_2019_6"
          },
          {
                "id": "53608",
                "title": "X-Force (2019) #6",
                "digitalBookId": "53608",
                "marvelIssueId": "76794",
                "slug": "x-force_2019_6"
          },
          {
                "id": "53606",
                "title": "Weapon Plus: World War IV #1",
                "digitalBookId": "53606",
                "marvelIssueId": "83536",
                "slug": "weapon_plus_world_war_iv_2020_1"
          },
          {
                "id": "53609",
                "title": "X-Men (2019) #5",
                "digitalBookId": "53609",
                "marvelIssueId": "76807",
                "slug": "x-men_2019_5"
          },
          {
                "id": "53985",
                "title": "Marauders (2019) #7",
                "digitalBookId": "53985",
                "marvelIssueId": "78401",
                "slug": "marauders_2019_7"
          },
          {
                "id": "53954",
                "title": "Excalibur (2019) #7",
                "digitalBookId": "53954",
                "marvelIssueId": "78388",
                "slug": "excalibur_2019_7"
          },
          {
                "id": "54082",
                "title": "X-Force (2019) #7",
                "digitalBookId": "54082",
                "marvelIssueId": "76795",
                "slug": "x-force_2019_7"
          },
          {
                "id": "53610",
                "title": "X-Men (2019) #6",
                "digitalBookId": "53610",
                "marvelIssueId": "79944",
                "slug": "x-men_2019_6"
          },
          {
                "id": "51478",
                "title": "Savage Avengers #0",
                "digitalBookId": "51478",
                "marvelIssueId": "75917",
                "slug": "free_comic_book_day_2019_1_2019_1"
          },
          {
                "id": "53986",
                "title": "Marauders (2019) #8",
                "digitalBookId": "53986",
                "marvelIssueId": "78402",
                "slug": "marauders_2019_8"
          },
          {
                "id": "53996",
                "title": "New Mutants (2019) #7",
                "digitalBookId": "53996",
                "marvelIssueId": "76763",
                "slug": "new_mutants_2019_7"
          },
          {
                "id": "49719",
                "title": "Deadpool (2018) #6",
                "digitalBookId": "49719",
                "marvelIssueId": "68153",
                "slug": "deadpool_2018_6"
          },
          {
                "id": "53964",
                "title": "Giant-Size X-Men: Jean Grey and Emma Frost #1",
                "digitalBookId": "53964",
                "marvelIssueId": "82527",
                "slug": "giant-size_x-men_jean_grey_and_emma_frost_2020_1"
          },
          {
                "id": "54084",
                "title": "X-Men (2019) #7",
                "digitalBookId": "54084",
                "marvelIssueId": "79945",
                "slug": "x-men_2019_7"
          },
          {
                "id": "54083",
                "title": "X-Force (2019) #8",
                "digitalBookId": "54083",
                "marvelIssueId": "76796",
                "slug": "x-force_2019_8"
          },
          {
                "id": "53997",
                "title": "New Mutants (2019) #8",
                "digitalBookId": "53997",
                "marvelIssueId": "76764",
                "slug": "new_mutants_2019_8"
          },
          {
                "id": "54255",
                "title": "Excalibur (2019) #8",
                "digitalBookId": "54255",
                "marvelIssueId": "78389",
                "slug": "excalibur_2019_8"
          },
          {
                "id": "54279",
                "title": "Marauders (2019) #9",
                "digitalBookId": "54279",
                "marvelIssueId": "78403",
                "slug": "marauders_2019_9"
          },
          {
                "id": "54246",
                "title": "Cable (2020) #1",
                "digitalBookId": "54246",
                "marvelIssueId": "78653",
                "slug": "cable_2020_1"
          },
          {
                "id": "54306",
                "title": "New Mutants (2019) #9",
                "digitalBookId": "54306",
                "marvelIssueId": "76765",
                "slug": "new_mutants_2019_9"
          },
          {
                "id": "54357",
                "title": "X-Men (2019) #8",
                "digitalBookId": "54357",
                "marvelIssueId": "79946",
                "slug": "x-men_2019_8"
          },
          {
                "id": "54256",
                "title": "Excalibur (2019) #9",
                "digitalBookId": "54256",
                "marvelIssueId": "78390",
                "slug": "excalibur_2019_9"
          },
          {
                "id": "54356",
                "title": "X-Force (2019) #9",
                "digitalBookId": "54356",
                "marvelIssueId": "76797",
                "slug": "x-force_2019_9"
          },
          {
                "id": "54264",
                "title": "Giant-Size X-Men: Nightcrawler #1",
                "digitalBookId": "54264",
                "marvelIssueId": "82506",
                "slug": "giant-size_x-men_nightcrawler_2020_1"
          },
          {
                "id": "54268",
                "title": "Hellions (2020) #1",
                "digitalBookId": "54268",
                "marvelIssueId": "85938",
                "slug": "hellions_2020_1"
          },
          {
                "id": "54355",
                "title": "Wolverine (2020) #2",
                "digitalBookId": "54355",
                "marvelIssueId": "78725",
                "slug": "wolverine_2020_2"
          },
          {
                "id": "54358",
                "title": "X-Men (2019) #9",
                "digitalBookId": "54358",
                "marvelIssueId": "79947",
                "slug": "x-men_2019_9"
          },
          {
                "id": "54612",
                "title": "Excalibur (2019) #10",
                "digitalBookId": "54612",
                "marvelIssueId": "78391",
                "slug": "excalibur_2019_10"
          },
          {
                "id": "53934",
                "title": "Black Cat (2019) #9",
                "digitalBookId": "53934",
                "marvelIssueId": "76160",
                "slug": "black_cat_2019_9"
          },
          {
                "id": "54243",
                "title": "Black Cat (2019) #10",
                "digitalBookId": "54243",
                "marvelIssueId": "76161",
                "slug": "black_cat_2019_10"
          },
          {
                "id": "54637",
                "title": "New Mutants (2019) #10",
                "digitalBookId": "54637",
                "marvelIssueId": "76766",
                "slug": "new_mutants_2019_10"
          },
          {
                "id": "54627",
                "title": "Marauders (2019) #10",
                "digitalBookId": "54627",
                "marvelIssueId": "78404",
                "slug": "marauders_2019_10"
          },
          {
                "id": "54669",
                "title": "X-Force (2019) #10",
                "digitalBookId": "54669",
                "marvelIssueId": "76798",
                "slug": "x-force_2019_10"
          },
          {
                "id": "54617",
                "title": "Giant-Size X-Men: Magneto #1",
                "digitalBookId": "54617",
                "marvelIssueId": "82502",
                "slug": "giant-size_x-men_magneto_2020_1"
          },
          {
                "id": "54261",
                "title": "Free Comic Book Day 2020 \u2013 X-Men",
                "digitalBookId": "54261",
                "marvelIssueId": "85662",
                "slug": "free_comic_book_day_x-men_2020_1"
          },
          {
                "id": "54916",
                "title": "New Mutants (2019) #11",
                "digitalBookId": "54916",
                "marvelIssueId": "76767",
                "slug": "new_mutants_2019_11"
          },
          {
                "id": "54667",
                "title": "Wolverine (2020) #3",
                "digitalBookId": "54667",
                "marvelIssueId": "78726",
                "slug": "wolverine_2020_3"
          },
          {
                "id": "54621",
                "title": "Hellions (2020) #2",
                "digitalBookId": "54621",
                "marvelIssueId": "85940",
                "slug": "hellions_2020_2"
          },
          {
                "id": "54670",
                "title": "X-Men (2019) #10",
                "digitalBookId": "54670",
                "marvelIssueId": "79948",
                "slug": "x-men_2019_10"
          },
          {
                "id": "54883",
                "title": "Empyre: X-Men (2020) #1",
                "digitalBookId": "54883",
                "marvelIssueId": "88646",
                "slug": "empyre_x-men_2020_1"
          },
          {
                "id": "54884",
                "title": "Empyre: X-Men (2020) #2",
                "digitalBookId": "54884",
                "marvelIssueId": "88647",
                "slug": "empyre_x-men_2020_2"
          },
          {
                "id": "55082",
                "title": "Empyre: X-Men (2020) #3",
                "digitalBookId": "55082",
                "marvelIssueId": "88648",
                "slug": "empyre_x-men_2020_3"
          },
          {
                "id": "55083",
                "title": "Empyre: X-Men (2020) #4",
                "digitalBookId": "55083",
                "marvelIssueId": "88649",
                "slug": "empyre_x-men_2020_4"
          },
          {
                "id": "54946",
                "title": "X-Men (2019) #11",
                "digitalBookId": "54946",
                "marvelIssueId": "79949",
                "slug": "x-men_2019_11"
          },
          {
                "id": "55412",
                "title": "Immortal She-Hulk #1",
                "digitalBookId": "55412",
                "marvelIssueId": "78698",
                "slug": "immortal_she-hulk_2020_1"
          },
          {
                "id": "54668",
                "title": "X-Factor (2020) #1",
                "digitalBookId": "54668",
                "marvelIssueId": "78746",
                "slug": "x-factor_2020_1"
          },
          {
                "id": "54588",
                "title": "Cable (2020) #2",
                "digitalBookId": "54588",
                "marvelIssueId": "78654",
                "slug": "cable_2020_2"
          },
          {
                "id": "54892",
                "title": "Giant-Size X-Men: Fantomex #1",
                "digitalBookId": "54892",
                "marvelIssueId": "82526",
                "slug": "giant-size_x-men_fantomex_2020_1"
          },
          {
                "id": "54904",
                "title": "Marauders (2019) #11",
                "digitalBookId": "54904",
                "marvelIssueId": "78405",
                "slug": "marauders_2019_11"
          },
          {
                "id": "54945",
                "title": "X-Force (2019) #11",
                "digitalBookId": "54945",
                "marvelIssueId": "76799",
                "slug": "x-force_2019_11"
          },
          {
                "id": "54860",
                "title": "Cable (2020) #3",
                "digitalBookId": "54860",
                "marvelIssueId": "78655",
                "slug": "cable_2020_3"
          },
          {
                "id": "55060",
                "title": "Cable (2020) #4",
                "digitalBookId": "55060",
                "marvelIssueId": "78656",
                "slug": "cable_2020_4"
          },
          {
                "id": "54943",
                "title": "Wolverine (2020) #4",
                "digitalBookId": "54943",
                "marvelIssueId": "78727",
                "slug": "wolverine_2020_4"
          },
          {
                "id": "55139",
                "title": "Wolverine (2020) #5",
                "digitalBookId": "55139",
                "marvelIssueId": "78728",
                "slug": "wolverine_2020_5"
          },
          {
                "id": "54896",
                "title": "Hellions (2020) #3",
                "digitalBookId": "54896",
                "marvelIssueId": "85942",
                "slug": "hellions_2020_3"
          },
          {
                "id": "54944",
                "title": "X-Factor (2020) #2",
                "digitalBookId": "54944",
                "marvelIssueId": "78747",
                "slug": "x-factor_2020_2"
          },
          {
                "id": "55140",
                "title": "X-Factor (2020) #3",
                "digitalBookId": "55140",
                "marvelIssueId": "78748",
                "slug": "x-factor_2020_3"
          },
          {
                "id": "55107",
                "title": "New Mutants (2019) #12",
                "digitalBookId": "55107",
                "marvelIssueId": "76768",
                "slug": "new_mutants_2019_12"
          },
          {
                "id": "55141",
                "title": "X-Force (2019) #12",
                "digitalBookId": "55141",
                "marvelIssueId": "76800",
                "slug": "x-force_2019_12"
          },
          {
                "id": "55100",
                "title": "Marauders (2019) #12",
                "digitalBookId": "55100",
                "marvelIssueId": "90080",
                "slug": "marauders_2019_12"
          },
          {
                "id": "55092",
                "title": "Hellions (2020) #4",
                "digitalBookId": "55092",
                "marvelIssueId": "85943",
                "slug": "hellions_2020_4"
          },
          {
                "id": "54901",
                "title": "Juggernaut (2020) #1",
                "digitalBookId": "54901",
                "marvelIssueId": "83413",
                "slug": "juggernaut_2020_1"
          },
          {
                "id": "55097",
                "title": "Juggernaut (2020) #2",
                "digitalBookId": "55097",
                "marvelIssueId": "83415",
                "slug": "juggernaut_2020_2"
          },
          {
                "id": "55693",
                "title": "Juggernaut (2020) #3",
                "digitalBookId": "55693",
                "marvelIssueId": "83416",
                "slug": "juggernaut_2020_3"
          },
          {
                "id": "55806",
                "title": "Juggernaut (2020) #4",
                "digitalBookId": "55806",
                "marvelIssueId": "83417",
                "slug": "juggernaut_2020_4"
          },
          {
                "id": "56024",
                "title": "Juggernaut (2020) #5",
                "digitalBookId": "56024",
                "marvelIssueId": "83418",
                "slug": "juggernaut_2020_5"
          },
          {
                "id": "55698",
                "title": "Marvel Voices: Indigenous Voices #1",
                "digitalBookId": "55698",
                "marvelIssueId": "91838",
                "slug": "marvels_voices_indigenous_voices_2020_1"
          },
          {
                "id": "55545",
                "title": "Avengers (2018) #37",
                "digitalBookId": "55545",
                "marvelIssueId": "77940",
                "slug": "avengers_2018_37"
          },
          {
                "id": "54921",
                "title": "Savage Avengers (2019) #13",
                "digitalBookId": "54921",
                "marvelIssueId": "78704",
                "slug": "savage_avengers_2019_13"
          },
          {
                "id": "55089",
                "title": "Giant-Size X-Men: Storm #1",
                "digitalBookId": "55089",
                "marvelIssueId": "82514",
                "slug": "giant-size_x-men_storm_2020_1"
          },
          {
                "id": "54885",
                "title": "Excalibur (2019) #11",
                "digitalBookId": "54885",
                "marvelIssueId": "78392",
                "slug": "excalibur_2019_11"
          },
          {
                "id": "55084",
                "title": "Excalibur (2019) #12",
                "digitalBookId": "55084",
                "marvelIssueId": "84380",
                "slug": "excalibur_2019_12"
          },
          {
                "id": "55142",
                "title": "X-Men (2019) #12",
                "digitalBookId": "55142",
                "marvelIssueId": "79950",
                "slug": "x-men_2019_12"
          },
          {
                "id": "55417",
                "title": "X of Swords: Creation (2020) #1",
                "digitalBookId": "55417",
                "marvelIssueId": "84337",
                "slug": "x_of_swords_creation_2020_1"
          },
          {
                "id": "55438",
                "title": "X-Factor (2020) #4",
                "digitalBookId": "55438",
                "marvelIssueId": "78749",
                "slug": "x-factor_2020_4"
          },
          {
                "id": "55573",
                "title": "Wolverine (2020) #6",
                "digitalBookId": "55573",
                "marvelIssueId": "78729",
                "slug": "wolverine_2020_6"
          },
          {
                "id": "55575",
                "title": "X-Force (2019) #13",
                "digitalBookId": "55575",
                "marvelIssueId": "90131",
                "slug": "x-force_2019_13"
          },
          {
                "id": "55559",
                "title": "Marauders (2019) #13",
                "digitalBookId": "55559",
                "marvelIssueId": "90081",
                "slug": "marauders_2019_13"
          },
          {
                "id": "55554",
                "title": "Hellions (2020) #5",
                "digitalBookId": "55554",
                "marvelIssueId": "85944",
                "slug": "hellions_2020_5"
          },
          {
                "id": "55560",
                "title": "New Mutants (2019) #13",
                "digitalBookId": "55560",
                "marvelIssueId": "90449",
                "slug": "new_mutants_2019_13"
          },
          {
                "id": "55546",
                "title": "Cable (2020) #5",
                "digitalBookId": "55546",
                "marvelIssueId": "78657",
                "slug": "cable_2020_5"
          },
          {
                "id": "55550",
                "title": "Excalibur (2019) #13",
                "digitalBookId": "55550",
                "marvelIssueId": "84381",
                "slug": "excalibur_2019_13"
          },
          {
                "id": "55576",
                "title": "X-Men (2019) #13",
                "digitalBookId": "55576",
                "marvelIssueId": "84427",
                "slug": "x-men_2019_13"
          },
          {
                "id": "55574",
                "title": "X of Swords: Stasis (2020) #1",
                "digitalBookId": "55574",
                "marvelIssueId": "84338",
                "slug": "x_of_swords_stasis_2020_1"
          },
          {
                "id": "55717",
                "title": "X-Men (2019) #14",
                "digitalBookId": "55717",
                "marvelIssueId": "84428",
                "slug": "x-men_2019_14"
          },
          {
                "id": "55695",
                "title": "Marauders (2019) #14",
                "digitalBookId": "55695",
                "marvelIssueId": "90082",
                "slug": "marauders_2019_14"
          },
          {
                "id": "55696",
                "title": "Marauders (2019) #15",
                "digitalBookId": "55696",
                "marvelIssueId": "90083",
                "slug": "marauders_2019_15"
          },
          {
                "id": "55685",
                "title": "Excalibur (2019) #14",
                "digitalBookId": "55685",
                "marvelIssueId": "84382",
                "slug": "excalibur_2019_14"
          },
          {
                "id": "55713",
                "title": "Wolverine (2020) #7",
                "digitalBookId": "55713",
                "marvelIssueId": "78730",
                "slug": "wolverine_2020_7"
          },
          {
                "id": "55716",
                "title": "X-Force (2019) #14",
                "digitalBookId": "55716",
                "marvelIssueId": "90132",
                "slug": "x-force_2019_14"
          },
          {
                "id": "55690",
                "title": "Hellions (2020) #6",
                "digitalBookId": "55690",
                "marvelIssueId": "85945",
                "slug": "hellions_2020_6"
          },
          {
                "id": "55680",
                "title": "Cable (2020) #6",
                "digitalBookId": "55680",
                "marvelIssueId": "78658",
                "slug": "cable_2020_6"
          },
          {
                "id": "55718",
                "title": "X-Men (2019) #15",
                "digitalBookId": "55718",
                "marvelIssueId": "84429",
                "slug": "x-men_2019_15"
          },
          {
                "id": "55686",
                "title": "Excalibur (2019) #15",
                "digitalBookId": "55686",
                "marvelIssueId": "84383",
                "slug": "excalibur_2019_15"
          },
          {
                "id": "55715",
                "title": "X of Swords: Destruction (2020) #1",
                "digitalBookId": "55715",
                "marvelIssueId": "84339",
                "slug": "x_of_swords_destruction_2020_1"
          },
          {
                "id": "55551",
                "title": "Fantastic Four (2018) #25",
                "digitalBookId": "55551",
                "marvelIssueId": "77325",
                "slug": "fantastic_four_2018_25"
          },
          {
                "id": "55687",
                "title": "Fantastic Four (2018) #26",
                "digitalBookId": "55687",
                "marvelIssueId": "77326",
                "slug": "fantastic_four_2018_26"
          }
    ],
  },
];

export function getStoryline(slug: string): Storyline | undefined {
  return STORYLINES.find((s) => s.slug === slug);
}
