// AUTO-GENERATED by scripts/generate-comics-data.mjs.
// Source: ~/Code/hickman-xmen/{lookup,applinks,drns}.json
// Re-run the script if the underlying reading order changes.

export interface ComicIssue {
  id: string;
  title: string;
  digitalBookId: string;
  marvelIssueId: string;
  slug: string;
  drn: string | null;
  sourceId: string | null;
}

export interface Storyline {
  slug: string;
  title: string;
  description?: string;
  issues: ComicIssue[];
}

export const STORYLINES: Storyline[] = [
  {
    slug: "hickman-x-men",
    title: "Jonathan Hickman's X-Men",
    description:
      "House of X / Powers of X through the X of Swords crossover. 149 issues.",
    issues: [
          {
                "id": "51975",
                "title": "House of X #1",
                "digitalBookId": "51975",
                "marvelIssueId": "72984",
                "slug": "house_of_x_2019_1",
                "drn": "drn:src:marvel:unison::prod:6e60b594-548f-4e50-92ab-cbfea2866b72",
                "sourceId": "72984"
          },
          {
                "id": "51997",
                "title": "Powers of X #1",
                "digitalBookId": "51997",
                "marvelIssueId": "72991",
                "slug": "powers_of_x_2019_1",
                "drn": "drn:src:marvel:unison::prod:4007758e-719c-4cd2-afe8-102206a95a38",
                "sourceId": "72991"
          },
          {
                "id": "52316",
                "title": "House of X #2",
                "digitalBookId": "52316",
                "marvelIssueId": "72985",
                "slug": "house_of_x_2019_2",
                "drn": "drn:src:marvel:unison::prod:01097952-6ab2-46cb-9c51-d5105156c064",
                "sourceId": "72985"
          },
          {
                "id": "52353",
                "title": "Powers of X #2",
                "digitalBookId": "52353",
                "marvelIssueId": "72992",
                "slug": "powers_of_x_2019_2",
                "drn": "drn:src:marvel:unison::prod:d906d74f-b485-4965-8105-a27383a60827",
                "sourceId": "72992"
          },
          {
                "id": "52382",
                "title": "Powers of X #3",
                "digitalBookId": "52382",
                "marvelIssueId": "72993",
                "slug": "powers_of_x_2019_3",
                "drn": "drn:src:marvel:unison::prod:6fa70df0-225b-4e82-ac62-ca3d91b76800",
                "sourceId": "72993"
          },
          {
                "id": "52403",
                "title": "House of X #3",
                "digitalBookId": "52403",
                "marvelIssueId": "72986",
                "slug": "house_of_x_2019_3",
                "drn": "drn:src:marvel:unison::prod:aa58c741-3658-40ae-b9ef-393b7d1b794d",
                "sourceId": "72986"
          },
          {
                "id": "52491",
                "title": "House of X #4",
                "digitalBookId": "52491",
                "marvelIssueId": "72987",
                "slug": "house_of_x_2019_4",
                "drn": "drn:src:marvel:unison::prod:6f3ee19a-1e62-4368-aa21-9e672a2bf2fb",
                "sourceId": "72987"
          },
          {
                "id": "52319",
                "title": "Marvel Comics #1000",
                "digitalBookId": "52319",
                "marvelIssueId": "75125",
                "slug": "marvel_comics_2019_1000",
                "drn": "drn:src:marvel:unison::prod:464bf652-9b03-4a53-9e70-9a243625d5b4",
                "sourceId": "75125"
          },
          {
                "id": "52537",
                "title": "Powers of X #4",
                "digitalBookId": "52537",
                "marvelIssueId": "72994",
                "slug": "powers_of_x_2019_4",
                "drn": "drn:src:marvel:unison::prod:a2cffcd1-237a-488a-9bc3-90a926b5bda3",
                "sourceId": "72994"
          },
          {
                "id": "52492",
                "title": "House of X #5",
                "digitalBookId": "52492",
                "marvelIssueId": "72988",
                "slug": "house_of_x_2019_5",
                "drn": "drn:src:marvel:unison::prod:7b132dc0-17cd-489f-8417-222a8463548e",
                "sourceId": "72988"
          },
          {
                "id": "52538",
                "title": "Powers of X #5",
                "digitalBookId": "52538",
                "marvelIssueId": "72995",
                "slug": "powers_of_x_2019_5",
                "drn": "drn:src:marvel:unison::prod:11a48834-0cf3-4be6-b189-741c2555835a",
                "sourceId": "72995"
          },
          {
                "id": "52801",
                "title": "House of X #6",
                "digitalBookId": "52801",
                "marvelIssueId": "72989",
                "slug": "house_of_x_2019_6",
                "drn": "drn:src:marvel:unison::prod:ce22cbe2-cac7-4c10-a11c-12f50d8c8582",
                "sourceId": "72989"
          },
          {
                "id": "52701",
                "title": "Powers of X #6",
                "digitalBookId": "52701",
                "marvelIssueId": "72996",
                "slug": "powers_of_x_2019_6",
                "drn": "drn:src:marvel:unison::prod:a1fbd79e-40e7-42dd-b729-c30b32c1e4ff",
                "sourceId": "72996"
          },
          {
                "id": "52818",
                "title": "X-Men (2019) #1",
                "digitalBookId": "52818",
                "marvelIssueId": "76803",
                "slug": "x-men_2019_1",
                "drn": "drn:src:marvel:unison::prod:b08e896a-8a3a-42f6-a805-104520b9a706",
                "sourceId": "76803"
          },
          {
                "id": "52697",
                "title": "Marauders (2019) #1",
                "digitalBookId": "52697",
                "marvelIssueId": "76750",
                "slug": "marauders_2019_1",
                "drn": "drn:src:marvel:unison::prod:9316b1d5-f1ca-4b5d-9429-80d8c1cfa570",
                "sourceId": "76750"
          },
          {
                "id": "52787",
                "title": "Excalibur (2019) #1",
                "digitalBookId": "52787",
                "marvelIssueId": "76729",
                "slug": "excalibur_2019_1",
                "drn": "drn:src:marvel:unison::prod:d5e73a80-dd3f-4a53-8567-20f803f42e2c",
                "sourceId": "76729"
          },
          {
                "id": "53011",
                "title": "New Mutants (2019) #1",
                "digitalBookId": "53011",
                "marvelIssueId": "76757",
                "slug": "new_mutants_2019_1",
                "drn": "drn:src:marvel:unison::prod:d78340fc-caea-4bf9-bd48-62106430da0a",
                "sourceId": "76757"
          },
          {
                "id": "53038",
                "title": "X-Force (2019) #1",
                "digitalBookId": "53038",
                "marvelIssueId": "76789",
                "slug": "x-force_2019_1",
                "drn": "drn:src:marvel:unison::prod:79978cd0-5d01-4ca2-bdac-ca74a2e790f8",
                "sourceId": "76789"
          },
          {
                "id": "52984",
                "title": "Fallen Angels (2019) #1",
                "digitalBookId": "52984",
                "marvelIssueId": "76742",
                "slug": "fallen_angels_2019_1",
                "drn": "drn:src:marvel:unison::prod:62952170-24dc-4686-b1a8-6b6d23ec785a",
                "sourceId": "76742"
          },
          {
                "id": "53040",
                "title": "X-Men (2019) #2",
                "digitalBookId": "53040",
                "marvelIssueId": "76804",
                "slug": "x-men_2019_2",
                "drn": "drn:src:marvel:unison::prod:b70f7589-f7b5-4460-8530-e9e4f5bdcc79",
                "sourceId": "76804"
          },
          {
                "id": "53006",
                "title": "Marauders (2019) #2",
                "digitalBookId": "53006",
                "marvelIssueId": "76751",
                "slug": "marauders_2019_2",
                "drn": "drn:src:marvel:unison::prod:57f6f587-f69b-4a93-9320-9b0c3a4e2cc4",
                "sourceId": "76751"
          },
          {
                "id": "52983",
                "title": "Excalibur (2019) #2",
                "digitalBookId": "52983",
                "marvelIssueId": "76730",
                "slug": "excalibur_2019_2",
                "drn": "drn:src:marvel:unison::prod:55ab0bef-f125-4c97-8908-552afc404dca",
                "sourceId": "76730"
          },
          {
                "id": "53012",
                "title": "New Mutants (2019) #2",
                "digitalBookId": "53012",
                "marvelIssueId": "76758",
                "slug": "new_mutants_2019_2",
                "drn": "drn:src:marvel:unison::prod:389af76a-1174-4220-a755-6007fcd34e75",
                "sourceId": "76758"
          },
          {
                "id": "53039",
                "title": "X-Force (2019) #2",
                "digitalBookId": "53039",
                "marvelIssueId": "76790",
                "slug": "x-force_2019_2",
                "drn": "drn:src:marvel:unison::prod:d10088cd-379f-43fa-906f-3cff7aa25247",
                "sourceId": "76790"
          },
          {
                "id": "52985",
                "title": "Fallen Angels (2019) #2",
                "digitalBookId": "52985",
                "marvelIssueId": "76743",
                "slug": "fallen_angels_2019_2",
                "drn": "drn:src:marvel:unison::prod:15c999db-32ef-4689-a867-8b508d3db62d",
                "sourceId": "76743"
          },
          {
                "id": "53309",
                "title": "X-Men (2019) #3",
                "digitalBookId": "53309",
                "marvelIssueId": "76805",
                "slug": "x-men_2019_3",
                "drn": "drn:src:marvel:unison::prod:4f6d6998-9e47-4686-ad76-f5681aec3689",
                "sourceId": "76805"
          },
          {
                "id": "53267",
                "title": "Marauders (2019) #3",
                "digitalBookId": "53267",
                "marvelIssueId": "76752",
                "slug": "marauders_2019_3",
                "drn": "drn:src:marvel:unison::prod:4d8f07ea-c0a4-4273-a1c5-f747c51e4dd8",
                "sourceId": "76752"
          },
          {
                "id": "53233",
                "title": "Excalibur (2019) #3",
                "digitalBookId": "53233",
                "marvelIssueId": "76731",
                "slug": "excalibur_2019_3",
                "drn": "drn:src:marvel:unison::prod:16d6fa0c-2cdd-470d-8464-20a4fd231220",
                "sourceId": "76731"
          },
          {
                "id": "53275",
                "title": "New Mutants (2019) #3",
                "digitalBookId": "53275",
                "marvelIssueId": "76759",
                "slug": "new_mutants_2019_3",
                "drn": "drn:src:marvel:unison::prod:104b58e2-4f9b-444e-bb21-6f6f4a45da79",
                "sourceId": "76759"
          },
          {
                "id": "53307",
                "title": "X-Force (2019) #3",
                "digitalBookId": "53307",
                "marvelIssueId": "76791",
                "slug": "x-force_2019_3",
                "drn": "drn:src:marvel:unison::prod:815e606c-0f9a-4322-8f29-8152031e7eeb",
                "sourceId": "76791"
          },
          {
                "id": "53241",
                "title": "Fallen Angels (2019) #3",
                "digitalBookId": "53241",
                "marvelIssueId": "76744",
                "slug": "fallen_angels_2019_3",
                "drn": "drn:src:marvel:unison::prod:82e8b823-3ba0-43d3-ac0c-b719c1c51d17",
                "sourceId": "76744"
          },
          {
                "id": "53268",
                "title": "Marauders (2019) #4",
                "digitalBookId": "53268",
                "marvelIssueId": "76753",
                "slug": "marauders_2019_4",
                "drn": "drn:src:marvel:unison::prod:00b90e86-047f-4688-a063-6ab096ddc528",
                "sourceId": "76753"
          },
          {
                "id": "53308",
                "title": "X-Force (2019) #4",
                "digitalBookId": "53308",
                "marvelIssueId": "76792",
                "slug": "x-force_2019_4",
                "drn": "drn:src:marvel:unison::prod:24643c2c-0f54-4c03-80ac-a8030ea456d5",
                "sourceId": "76792"
          },
          {
                "id": "53274",
                "title": "New Mutants (2019) #4",
                "digitalBookId": "53274",
                "marvelIssueId": "76760",
                "slug": "new_mutants_2019_4",
                "drn": "drn:src:marvel:unison::prod:4789eab1-6773-4e4d-926f-9ad2994bd5dc",
                "sourceId": "76760"
          },
          {
                "id": "53239",
                "title": "Excalibur (2019) #4",
                "digitalBookId": "53239",
                "marvelIssueId": "76732",
                "slug": "excalibur_2019_4",
                "drn": "drn:src:marvel:unison::prod:c7f65de3-6260-4e1f-8bd6-3a8a42c7883c",
                "sourceId": "76732"
          },
          {
                "id": "53245",
                "title": "Fallen Angels (2019) #4",
                "digitalBookId": "53245",
                "marvelIssueId": "76745",
                "slug": "fallen_angels_2019_4",
                "drn": "drn:src:marvel:unison::prod:aeb021ef-4ac4-4899-8408-37d3da777a62",
                "sourceId": "76745"
          },
          {
                "id": "53263",
                "title": "Incoming #1",
                "digitalBookId": "53263",
                "marvelIssueId": "76984",
                "slug": "incoming_2019_1",
                "drn": "drn:src:marvel:unison::prod:6223f9f6-a5e3-4a64-aec7-b2bbe0d65937",
                "sourceId": "76984"
          },
          {
                "id": "53258",
                "title": "Gwenpool Strikes Back #5",
                "digitalBookId": "53258",
                "marvelIssueId": "76055",
                "slug": "gwenpool_strikes_back_2019_5",
                "drn": "drn:src:marvel:unison::prod:7c784324-5101-4466-a41f-fe88cb0f866e",
                "sourceId": "76055"
          },
          {
                "id": "53310",
                "title": "X-Men (2019) #4",
                "digitalBookId": "53310",
                "marvelIssueId": "76806",
                "slug": "x-men_2019_4",
                "drn": "drn:src:marvel:unison::prod:74ef2633-f788-4cf7-ad47-d22331a3a774",
                "sourceId": "76806"
          },
          {
                "id": "53566",
                "title": "Marauders (2019) #5",
                "digitalBookId": "53566",
                "marvelIssueId": "76754",
                "slug": "marauders_2019_5",
                "drn": "drn:src:marvel:unison::prod:05e5ae32-3f41-48c5-b165-bc953b139452",
                "sourceId": "76754"
          },
          {
                "id": "53576",
                "title": "New Mutants (2019) #5",
                "digitalBookId": "53576",
                "marvelIssueId": "76761",
                "slug": "new_mutants_2019_5",
                "drn": "drn:src:marvel:unison::prod:67722d05-6233-436c-9ebf-2bbb31081779",
                "sourceId": "76761"
          },
          {
                "id": "52710",
                "title": "X-Force (2019) #5",
                "digitalBookId": "52710",
                "marvelIssueId": "76793",
                "slug": "x-force_2019_5",
                "drn": "drn:src:marvel:unison::prod:4f45d1db-80e1-494e-8860-c8aa84203b48",
                "sourceId": "76793"
          },
          {
                "id": "53548",
                "title": "Excalibur (2019) #5",
                "digitalBookId": "53548",
                "marvelIssueId": "76733",
                "slug": "excalibur_2019_5",
                "drn": "drn:src:marvel:unison::prod:82b2aeb8-f002-4629-87cf-686891d6e722",
                "sourceId": "76733"
          },
          {
                "id": "53550",
                "title": "Fallen Angels (2019) #5",
                "digitalBookId": "53550",
                "marvelIssueId": "76746",
                "slug": "fallen_angels_2019_5",
                "drn": "drn:src:marvel:unison::prod:45d4eda2-c3ff-4800-a2c6-5a00a6c7cd6c",
                "sourceId": "76746"
          },
          {
                "id": "53549",
                "title": "Excalibur (2019) #6",
                "digitalBookId": "53549",
                "marvelIssueId": "76734",
                "slug": "excalibur_2019_6",
                "drn": "drn:src:marvel:unison::prod:9044ffd7-f817-4c08-bb63-5fad7a93aff5",
                "sourceId": "76734"
          },
          {
                "id": "53991",
                "title": "Marvel's Voices #1",
                "digitalBookId": "53991",
                "marvelIssueId": "84188",
                "slug": "marvels_voices_2020_1",
                "drn": "drn:src:marvel:unison::prod:24572ac3-7c6b-4576-b097-cf51d60e9f7d",
                "sourceId": "84188"
          },
          {
                "id": "54085",
                "title": "X-Men/Fantastic Four (2020) #1",
                "digitalBookId": "54085",
                "marvelIssueId": "77993",
                "slug": "x-menfantastic_four_2020_1",
                "drn": "drn:src:marvel:unison::prod:7a019c6c-73e0-457d-8a6e-13657325ec00",
                "sourceId": "77993"
          },
          {
                "id": "54086",
                "title": "X-Men/Fantastic Four (2020) #2",
                "digitalBookId": "54086",
                "marvelIssueId": "77995",
                "slug": "x-menfantastic_four_2020_2",
                "drn": "drn:src:marvel:unison::prod:f041fce4-280b-49b2-aa16-a42a1d40282b",
                "sourceId": "77995"
          },
          {
                "id": "54359",
                "title": "X-Men/Fantastic Four (2020) #3",
                "digitalBookId": "54359",
                "marvelIssueId": "77996",
                "slug": "x-menfantastic_four_2020_3",
                "drn": "drn:src:marvel:unison::prod:a7af8808-7255-40f8-8902-dcb18b15a9f7",
                "sourceId": "77996"
          },
          {
                "id": "54671",
                "title": "X-Men/Fantastic Four (2020) #4",
                "digitalBookId": "54671",
                "marvelIssueId": "77997",
                "slug": "x-menfantastic_four_2020_4",
                "drn": "drn:src:marvel:unison::prod:8e91e7f7-8d46-4ff7-9358-6c5eae5817fd",
                "sourceId": "77997"
          },
          {
                "id": "54079",
                "title": "Wolverine (2020) #1",
                "digitalBookId": "54079",
                "marvelIssueId": "78724",
                "slug": "wolverine_2020_1",
                "drn": "drn:src:marvel:unison::prod:82117930-162b-4712-ac78-35e204a10b17",
                "sourceId": "78724"
          },
          {
                "id": "53567",
                "title": "Marauders (2019) #6",
                "digitalBookId": "53567",
                "marvelIssueId": "76755",
                "slug": "marauders_2019_6",
                "drn": "drn:src:marvel:unison::prod:4930ed0c-86b8-4304-947a-2808d8654f29",
                "sourceId": "76755"
          },
          {
                "id": "53551",
                "title": "Fallen Angels (2019) #6",
                "digitalBookId": "53551",
                "marvelIssueId": "76747",
                "slug": "fallen_angels_2019_6",
                "drn": "drn:src:marvel:unison::prod:c66bf8f0-eb93-405e-8d3f-d29c4d4661f0",
                "sourceId": "76747"
          },
          {
                "id": "53577",
                "title": "New Mutants (2019) #6",
                "digitalBookId": "53577",
                "marvelIssueId": "76762",
                "slug": "new_mutants_2019_6",
                "drn": "drn:src:marvel:unison::prod:a23c6c1e-8681-4fe0-ba5e-1ba18189a15c",
                "sourceId": "76762"
          },
          {
                "id": "53608",
                "title": "X-Force (2019) #6",
                "digitalBookId": "53608",
                "marvelIssueId": "76794",
                "slug": "x-force_2019_6",
                "drn": "drn:src:marvel:unison::prod:fe4513c0-1796-4cbe-874d-bd0828ce2a57",
                "sourceId": "76794"
          },
          {
                "id": "53606",
                "title": "Weapon Plus: World War IV #1",
                "digitalBookId": "53606",
                "marvelIssueId": "83536",
                "slug": "weapon_plus_world_war_iv_2020_1",
                "drn": "drn:src:marvel:unison::prod:1a3e74db-e6dd-43f8-9b87-9acee309fa00",
                "sourceId": "83536"
          },
          {
                "id": "53609",
                "title": "X-Men (2019) #5",
                "digitalBookId": "53609",
                "marvelIssueId": "76807",
                "slug": "x-men_2019_5",
                "drn": "drn:src:marvel:unison::prod:78d1d89d-2897-4959-8ccf-1b28230c3412",
                "sourceId": "76807"
          },
          {
                "id": "53985",
                "title": "Marauders (2019) #7",
                "digitalBookId": "53985",
                "marvelIssueId": "78401",
                "slug": "marauders_2019_7",
                "drn": "drn:src:marvel:unison::prod:46a6a858-772b-4468-92b5-55a74d61ec68",
                "sourceId": "78401"
          },
          {
                "id": "53954",
                "title": "Excalibur (2019) #7",
                "digitalBookId": "53954",
                "marvelIssueId": "78388",
                "slug": "excalibur_2019_7",
                "drn": "drn:src:marvel:unison::prod:9820d112-31bf-4235-b991-c63d57bdc6e7",
                "sourceId": "78388"
          },
          {
                "id": "54082",
                "title": "X-Force (2019) #7",
                "digitalBookId": "54082",
                "marvelIssueId": "76795",
                "slug": "x-force_2019_7",
                "drn": "drn:src:marvel:unison::prod:403371bc-52f6-4d1f-b9d2-25d49c56dcfd",
                "sourceId": "76795"
          },
          {
                "id": "53610",
                "title": "X-Men (2019) #6",
                "digitalBookId": "53610",
                "marvelIssueId": "79944",
                "slug": "x-men_2019_6",
                "drn": "drn:src:marvel:unison::prod:49e86984-6186-4f6b-b17d-e66de7756a84",
                "sourceId": "79944"
          },
          {
                "id": "51478",
                "title": "Savage Avengers #0",
                "digitalBookId": "51478",
                "marvelIssueId": "75917",
                "slug": "free_comic_book_day_2019_1_2019_1",
                "drn": "drn:src:marvel:unison::prod:3ebda134-20db-4b10-ad1a-c05839d6ead4",
                "sourceId": "75917"
          },
          {
                "id": "53986",
                "title": "Marauders (2019) #8",
                "digitalBookId": "53986",
                "marvelIssueId": "78402",
                "slug": "marauders_2019_8",
                "drn": "drn:src:marvel:unison::prod:54f1ac4b-a281-4867-bc62-918d08f19476",
                "sourceId": "78402"
          },
          {
                "id": "53996",
                "title": "New Mutants (2019) #7",
                "digitalBookId": "53996",
                "marvelIssueId": "76763",
                "slug": "new_mutants_2019_7",
                "drn": "drn:src:marvel:unison::prod:9beb27a8-4308-4a35-b7c8-18d1b2939ddb",
                "sourceId": "76763"
          },
          {
                "id": "49719",
                "title": "Deadpool (2018) #6",
                "digitalBookId": "49719",
                "marvelIssueId": "68153",
                "slug": "deadpool_2018_6",
                "drn": "drn:src:marvel:unison::prod:ad3737be-0f2a-4d07-9604-29d0d34307d0",
                "sourceId": "68153"
          },
          {
                "id": "53964",
                "title": "Giant-Size X-Men: Jean Grey and Emma Frost #1",
                "digitalBookId": "53964",
                "marvelIssueId": "82527",
                "slug": "giant-size_x-men_jean_grey_and_emma_frost_2020_1",
                "drn": "drn:src:marvel:unison::prod:2d230fb2-dbde-43d0-9eb2-34da83d02a39",
                "sourceId": "82527"
          },
          {
                "id": "54084",
                "title": "X-Men (2019) #7",
                "digitalBookId": "54084",
                "marvelIssueId": "79945",
                "slug": "x-men_2019_7",
                "drn": "drn:src:marvel:unison::prod:675bcdb8-6a23-4a1f-b375-a700600ba889",
                "sourceId": "79945"
          },
          {
                "id": "54083",
                "title": "X-Force (2019) #8",
                "digitalBookId": "54083",
                "marvelIssueId": "76796",
                "slug": "x-force_2019_8",
                "drn": "drn:src:marvel:unison::prod:1f226aa1-6d1b-44ef-b521-ef90d5736a10",
                "sourceId": "76796"
          },
          {
                "id": "53997",
                "title": "New Mutants (2019) #8",
                "digitalBookId": "53997",
                "marvelIssueId": "76764",
                "slug": "new_mutants_2019_8",
                "drn": "drn:src:marvel:unison::prod:39a37838-7ad0-41cd-97c4-b661f003aae6",
                "sourceId": "76764"
          },
          {
                "id": "54255",
                "title": "Excalibur (2019) #8",
                "digitalBookId": "54255",
                "marvelIssueId": "78389",
                "slug": "excalibur_2019_8",
                "drn": "drn:src:marvel:unison::prod:113889de-ffe2-4771-b2bf-58dbc9a4e7f2",
                "sourceId": "78389"
          },
          {
                "id": "54279",
                "title": "Marauders (2019) #9",
                "digitalBookId": "54279",
                "marvelIssueId": "78403",
                "slug": "marauders_2019_9",
                "drn": "drn:src:marvel:unison::prod:4f57733c-83c1-45b3-9ca8-7bd39f999ef5",
                "sourceId": "78403"
          },
          {
                "id": "54246",
                "title": "Cable (2020) #1",
                "digitalBookId": "54246",
                "marvelIssueId": "78653",
                "slug": "cable_2020_1",
                "drn": "drn:src:marvel:unison::prod:ea64f378-4872-4665-9dd4-0712d52450d7",
                "sourceId": "78653"
          },
          {
                "id": "54306",
                "title": "New Mutants (2019) #9",
                "digitalBookId": "54306",
                "marvelIssueId": "76765",
                "slug": "new_mutants_2019_9",
                "drn": "drn:src:marvel:unison::prod:8d3e5786-69e8-4e52-b2c4-03cba9275ef2",
                "sourceId": "76765"
          },
          {
                "id": "54357",
                "title": "X-Men (2019) #8",
                "digitalBookId": "54357",
                "marvelIssueId": "79946",
                "slug": "x-men_2019_8",
                "drn": "drn:src:marvel:unison::prod:b9cdfb94-407a-475d-910a-776d6404ee4a",
                "sourceId": "79946"
          },
          {
                "id": "54256",
                "title": "Excalibur (2019) #9",
                "digitalBookId": "54256",
                "marvelIssueId": "78390",
                "slug": "excalibur_2019_9",
                "drn": "drn:src:marvel:unison::prod:580c6087-fb25-4906-b8e0-540288881cf3",
                "sourceId": "78390"
          },
          {
                "id": "54356",
                "title": "X-Force (2019) #9",
                "digitalBookId": "54356",
                "marvelIssueId": "76797",
                "slug": "x-force_2019_9",
                "drn": "drn:src:marvel:unison::prod:5ffad203-3dfb-45a0-be09-11975d967eb3",
                "sourceId": "76797"
          },
          {
                "id": "54264",
                "title": "Giant-Size X-Men: Nightcrawler #1",
                "digitalBookId": "54264",
                "marvelIssueId": "82506",
                "slug": "giant-size_x-men_nightcrawler_2020_1",
                "drn": "drn:src:marvel:unison::prod:7c6fc0b9-df5d-4ce0-adb0-2e98f1330a2f",
                "sourceId": "82506"
          },
          {
                "id": "54268",
                "title": "Hellions (2020) #1",
                "digitalBookId": "54268",
                "marvelIssueId": "85938",
                "slug": "hellions_2020_1",
                "drn": "drn:src:marvel:unison::prod:2a3f6b4f-6e3b-4e0f-9dbd-20d1782a12e4",
                "sourceId": "85938"
          },
          {
                "id": "54355",
                "title": "Wolverine (2020) #2",
                "digitalBookId": "54355",
                "marvelIssueId": "78725",
                "slug": "wolverine_2020_2",
                "drn": "drn:src:marvel:unison::prod:1de9c550-8d5a-4158-ba45-663b5e4ada96",
                "sourceId": "78725"
          },
          {
                "id": "54358",
                "title": "X-Men (2019) #9",
                "digitalBookId": "54358",
                "marvelIssueId": "79947",
                "slug": "x-men_2019_9",
                "drn": "drn:src:marvel:unison::prod:dc2e9f2e-f683-49ad-9d53-91c624db3a05",
                "sourceId": "79947"
          },
          {
                "id": "54612",
                "title": "Excalibur (2019) #10",
                "digitalBookId": "54612",
                "marvelIssueId": "78391",
                "slug": "excalibur_2019_10",
                "drn": "drn:src:marvel:unison::prod:be426fea-2d15-43e0-9e09-2c4148466adf",
                "sourceId": "78391"
          },
          {
                "id": "53934",
                "title": "Black Cat (2019) #9",
                "digitalBookId": "53934",
                "marvelIssueId": "76160",
                "slug": "black_cat_2019_9",
                "drn": "drn:src:marvel:unison::prod:d3725a9a-96cd-419b-ae0e-58bb8af4c4a4",
                "sourceId": "76160"
          },
          {
                "id": "54243",
                "title": "Black Cat (2019) #10",
                "digitalBookId": "54243",
                "marvelIssueId": "76161",
                "slug": "black_cat_2019_10",
                "drn": "drn:src:marvel:unison::prod:2bf7e6af-5c62-4cf5-938b-8eacaa8f4879",
                "sourceId": "76161"
          },
          {
                "id": "54637",
                "title": "New Mutants (2019) #10",
                "digitalBookId": "54637",
                "marvelIssueId": "76766",
                "slug": "new_mutants_2019_10",
                "drn": "drn:src:marvel:unison::prod:1c175f7a-b4c0-48d9-836c-3c6ebfcaffb4",
                "sourceId": "76766"
          },
          {
                "id": "54627",
                "title": "Marauders (2019) #10",
                "digitalBookId": "54627",
                "marvelIssueId": "78404",
                "slug": "marauders_2019_10",
                "drn": "drn:src:marvel:unison::prod:5c8582c6-9244-4284-bf4e-0797b0a8f2d6",
                "sourceId": "78404"
          },
          {
                "id": "54669",
                "title": "X-Force (2019) #10",
                "digitalBookId": "54669",
                "marvelIssueId": "76798",
                "slug": "x-force_2019_10",
                "drn": "drn:src:marvel:unison::prod:f181d425-aee8-4d5f-a86e-039a11b05aea",
                "sourceId": "76798"
          },
          {
                "id": "54617",
                "title": "Giant-Size X-Men: Magneto #1",
                "digitalBookId": "54617",
                "marvelIssueId": "82502",
                "slug": "giant-size_x-men_magneto_2020_1",
                "drn": "drn:src:marvel:unison::prod:86848caa-b277-4678-913d-e2c99c673753",
                "sourceId": "82502"
          },
          {
                "id": "54261",
                "title": "Free Comic Book Day 2020 – X-Men",
                "digitalBookId": "54261",
                "marvelIssueId": "85662",
                "slug": "free_comic_book_day_x-men_2020_1",
                "drn": "drn:src:marvel:unison::prod:800f9071-2ff3-4bf9-acf2-a200226bcac7",
                "sourceId": "85662"
          },
          {
                "id": "54916",
                "title": "New Mutants (2019) #11",
                "digitalBookId": "54916",
                "marvelIssueId": "76767",
                "slug": "new_mutants_2019_11",
                "drn": "drn:src:marvel:unison::prod:c5dd503e-6341-4074-8445-cfbc2037621c",
                "sourceId": "76767"
          },
          {
                "id": "54667",
                "title": "Wolverine (2020) #3",
                "digitalBookId": "54667",
                "marvelIssueId": "78726",
                "slug": "wolverine_2020_3",
                "drn": "drn:src:marvel:unison::prod:7811443b-aca1-4465-945a-78779a3987ef",
                "sourceId": "78726"
          },
          {
                "id": "54621",
                "title": "Hellions (2020) #2",
                "digitalBookId": "54621",
                "marvelIssueId": "85940",
                "slug": "hellions_2020_2",
                "drn": "drn:src:marvel:unison::prod:6b5df1e0-b1d2-4898-a59c-36a895b4dfdd",
                "sourceId": "85940"
          },
          {
                "id": "54670",
                "title": "X-Men (2019) #10",
                "digitalBookId": "54670",
                "marvelIssueId": "79948",
                "slug": "x-men_2019_10",
                "drn": "drn:src:marvel:unison::prod:22f37fce-876c-492d-a414-9bbebdf1ebc1",
                "sourceId": "79948"
          },
          {
                "id": "54883",
                "title": "Empyre: X-Men (2020) #1",
                "digitalBookId": "54883",
                "marvelIssueId": "88646",
                "slug": "empyre_x-men_2020_1",
                "drn": "drn:src:marvel:unison::prod:1eabf10d-a4f7-440b-8e65-77e70a040303",
                "sourceId": "88646"
          },
          {
                "id": "54884",
                "title": "Empyre: X-Men (2020) #2",
                "digitalBookId": "54884",
                "marvelIssueId": "88647",
                "slug": "empyre_x-men_2020_2",
                "drn": "drn:src:marvel:unison::prod:52afd210-8d5e-47da-a5ae-7882975e2471",
                "sourceId": "88647"
          },
          {
                "id": "55082",
                "title": "Empyre: X-Men (2020) #3",
                "digitalBookId": "55082",
                "marvelIssueId": "88648",
                "slug": "empyre_x-men_2020_3",
                "drn": "drn:src:marvel:unison::prod:ed239cc4-4c72-4eb3-b9e0-babc0fa26725",
                "sourceId": "88648"
          },
          {
                "id": "55083",
                "title": "Empyre: X-Men (2020) #4",
                "digitalBookId": "55083",
                "marvelIssueId": "88649",
                "slug": "empyre_x-men_2020_4",
                "drn": "drn:src:marvel:unison::prod:7b312cd1-a2a3-4d29-9f14-5a0477ea8772",
                "sourceId": "88649"
          },
          {
                "id": "54946",
                "title": "X-Men (2019) #11",
                "digitalBookId": "54946",
                "marvelIssueId": "79949",
                "slug": "x-men_2019_11",
                "drn": "drn:src:marvel:unison::prod:5ef82b52-0fa9-494e-9653-b7e7fffa7c10",
                "sourceId": "79949"
          },
          {
                "id": "55412",
                "title": "Immortal She-Hulk #1",
                "digitalBookId": "55412",
                "marvelIssueId": "78698",
                "slug": "immortal_she-hulk_2020_1",
                "drn": "drn:src:marvel:unison::prod:b2739304-2ec5-4b95-a050-56508702e82f",
                "sourceId": "78698"
          },
          {
                "id": "54668",
                "title": "X-Factor (2020) #1",
                "digitalBookId": "54668",
                "marvelIssueId": "78746",
                "slug": "x-factor_2020_1",
                "drn": "drn:src:marvel:unison::prod:c0008eba-ca8f-4057-a6b1-4db2a5528247",
                "sourceId": "78746"
          },
          {
                "id": "54588",
                "title": "Cable (2020) #2",
                "digitalBookId": "54588",
                "marvelIssueId": "78654",
                "slug": "cable_2020_2",
                "drn": "drn:src:marvel:unison::prod:f82d2232-4e1c-4baa-90dd-b0a1fcbe03df",
                "sourceId": "78654"
          },
          {
                "id": "54892",
                "title": "Giant-Size X-Men: Fantomex #1",
                "digitalBookId": "54892",
                "marvelIssueId": "82526",
                "slug": "giant-size_x-men_fantomex_2020_1",
                "drn": "drn:src:marvel:unison::prod:6b3cfab8-b683-46fb-8b1a-fdf07860cf31",
                "sourceId": "82526"
          },
          {
                "id": "54904",
                "title": "Marauders (2019) #11",
                "digitalBookId": "54904",
                "marvelIssueId": "78405",
                "slug": "marauders_2019_11",
                "drn": "drn:src:marvel:unison::prod:562a9341-3bfa-409c-8f9f-637b17ffeaa7",
                "sourceId": "78405"
          },
          {
                "id": "54945",
                "title": "X-Force (2019) #11",
                "digitalBookId": "54945",
                "marvelIssueId": "76799",
                "slug": "x-force_2019_11",
                "drn": "drn:src:marvel:unison::prod:d8d7c719-0517-4101-8599-ce848838dd63",
                "sourceId": "76799"
          },
          {
                "id": "54860",
                "title": "Cable (2020) #3",
                "digitalBookId": "54860",
                "marvelIssueId": "78655",
                "slug": "cable_2020_3",
                "drn": "drn:src:marvel:unison::prod:d9009db8-9b82-46f7-95ef-c88d50076b74",
                "sourceId": "78655"
          },
          {
                "id": "55060",
                "title": "Cable (2020) #4",
                "digitalBookId": "55060",
                "marvelIssueId": "78656",
                "slug": "cable_2020_4",
                "drn": "drn:src:marvel:unison::prod:5f2a99ad-b695-4bcf-9d7c-2aa20952f711",
                "sourceId": "78656"
          },
          {
                "id": "54943",
                "title": "Wolverine (2020) #4",
                "digitalBookId": "54943",
                "marvelIssueId": "78727",
                "slug": "wolverine_2020_4",
                "drn": "drn:src:marvel:unison::prod:fb876173-6476-4ce8-81ba-263de00b7ca2",
                "sourceId": "78727"
          },
          {
                "id": "55139",
                "title": "Wolverine (2020) #5",
                "digitalBookId": "55139",
                "marvelIssueId": "78728",
                "slug": "wolverine_2020_5",
                "drn": "drn:src:marvel:unison::prod:8ab1cba4-7f11-4406-9210-8f068d887cba",
                "sourceId": "78728"
          },
          {
                "id": "54896",
                "title": "Hellions (2020) #3",
                "digitalBookId": "54896",
                "marvelIssueId": "85942",
                "slug": "hellions_2020_3",
                "drn": "drn:src:marvel:unison::prod:835707e4-faf6-43c3-b9c0-0ca26532adec",
                "sourceId": "85942"
          },
          {
                "id": "54944",
                "title": "X-Factor (2020) #2",
                "digitalBookId": "54944",
                "marvelIssueId": "78747",
                "slug": "x-factor_2020_2",
                "drn": "drn:src:marvel:unison::prod:53536695-99b0-4641-b598-2b6e9875cb84",
                "sourceId": "78747"
          },
          {
                "id": "55140",
                "title": "X-Factor (2020) #3",
                "digitalBookId": "55140",
                "marvelIssueId": "78748",
                "slug": "x-factor_2020_3",
                "drn": "drn:src:marvel:unison::prod:fc212139-06c2-4d02-a868-8045bc9544ef",
                "sourceId": "78748"
          },
          {
                "id": "55107",
                "title": "New Mutants (2019) #12",
                "digitalBookId": "55107",
                "marvelIssueId": "76768",
                "slug": "new_mutants_2019_12",
                "drn": "drn:src:marvel:unison::prod:2fa0f0ba-8bdd-4c52-bbe0-463286cda151",
                "sourceId": "76768"
          },
          {
                "id": "55141",
                "title": "X-Force (2019) #12",
                "digitalBookId": "55141",
                "marvelIssueId": "76800",
                "slug": "x-force_2019_12",
                "drn": "drn:src:marvel:unison::prod:619b1910-99d9-43a2-9eb5-ea8b03b947c7",
                "sourceId": "76800"
          },
          {
                "id": "55100",
                "title": "Marauders (2019) #12",
                "digitalBookId": "55100",
                "marvelIssueId": "90080",
                "slug": "marauders_2019_12",
                "drn": "drn:src:marvel:unison::prod:0aefcb9a-9c9b-4a66-8ce0-d1d38c117707",
                "sourceId": "90080"
          },
          {
                "id": "55092",
                "title": "Hellions (2020) #4",
                "digitalBookId": "55092",
                "marvelIssueId": "85943",
                "slug": "hellions_2020_4",
                "drn": "drn:src:marvel:unison::prod:6a5fc880-0f23-48d4-9adf-aa3883aff7de",
                "sourceId": "85943"
          },
          {
                "id": "54901",
                "title": "Juggernaut (2020) #1",
                "digitalBookId": "54901",
                "marvelIssueId": "83413",
                "slug": "juggernaut_2020_1",
                "drn": "drn:src:marvel:unison::prod:5e8b0842-eff2-4a09-9f86-77c555bd7d86",
                "sourceId": "83413"
          },
          {
                "id": "55097",
                "title": "Juggernaut (2020) #2",
                "digitalBookId": "55097",
                "marvelIssueId": "83415",
                "slug": "juggernaut_2020_2",
                "drn": "drn:src:marvel:unison::prod:d53bbe55-8b81-44e3-8c99-fc74fedf0efc",
                "sourceId": "83415"
          },
          {
                "id": "55693",
                "title": "Juggernaut (2020) #3",
                "digitalBookId": "55693",
                "marvelIssueId": "83416",
                "slug": "juggernaut_2020_3",
                "drn": "drn:src:marvel:unison::prod:22cee920-03e9-4c95-b09e-5df1c2216a45",
                "sourceId": "83416"
          },
          {
                "id": "55806",
                "title": "Juggernaut (2020) #4",
                "digitalBookId": "55806",
                "marvelIssueId": "83417",
                "slug": "juggernaut_2020_4",
                "drn": "drn:src:marvel:unison::prod:991cb724-47e6-4fa0-8eba-bc6a22598695",
                "sourceId": "83417"
          },
          {
                "id": "56024",
                "title": "Juggernaut (2020) #5",
                "digitalBookId": "56024",
                "marvelIssueId": "83418",
                "slug": "juggernaut_2020_5",
                "drn": "drn:src:marvel:unison::prod:61b9c761-ef17-4237-9609-b423db1eabac",
                "sourceId": "83418"
          },
          {
                "id": "55698",
                "title": "Marvel Voices: Indigenous Voices #1",
                "digitalBookId": "55698",
                "marvelIssueId": "91838",
                "slug": "marvels_voices_indigenous_voices_2020_1",
                "drn": "drn:src:marvel:unison::prod:17a6a8f9-d313-4630-907c-951f8a4224a1",
                "sourceId": "91838"
          },
          {
                "id": "55545",
                "title": "Avengers (2018) #37",
                "digitalBookId": "55545",
                "marvelIssueId": "77940",
                "slug": "avengers_2018_37",
                "drn": "drn:src:marvel:unison::prod:5a9037cd-f088-4104-80f4-c0acb8dbcf68",
                "sourceId": "77940"
          },
          {
                "id": "55089",
                "title": "Giant-Size X-Men: Storm #1",
                "digitalBookId": "55089",
                "marvelIssueId": "82514",
                "slug": "giant-size_x-men_storm_2020_1",
                "drn": "drn:src:marvel:unison::prod:1cfebc7b-1984-48f8-aa11-e473c3d9290e",
                "sourceId": "82514"
          },
          {
                "id": "54885",
                "title": "Excalibur (2019) #11",
                "digitalBookId": "54885",
                "marvelIssueId": "78392",
                "slug": "excalibur_2019_11",
                "drn": "drn:src:marvel:unison::prod:aabf2cc3-412f-466c-ae96-5ca5e571e540",
                "sourceId": "78392"
          },
          {
                "id": "55084",
                "title": "Excalibur (2019) #12",
                "digitalBookId": "55084",
                "marvelIssueId": "84380",
                "slug": "excalibur_2019_12",
                "drn": "drn:src:marvel:unison::prod:ace83136-6107-4d0b-9ce1-991e50cc66b2",
                "sourceId": "84380"
          },
          {
                "id": "55142",
                "title": "X-Men (2019) #12",
                "digitalBookId": "55142",
                "marvelIssueId": "79950",
                "slug": "x-men_2019_12",
                "drn": "drn:src:marvel:unison::prod:de9331b3-5551-405a-8a54-c58e0ace1a55",
                "sourceId": "79950"
          },
          {
                "id": "55417",
                "title": "X of Swords: Creation (2020) #1",
                "digitalBookId": "55417",
                "marvelIssueId": "84337",
                "slug": "x_of_swords_creation_2020_1",
                "drn": "drn:src:marvel:unison::prod:84698e87-60eb-4115-b19d-ca1dd0bde93f",
                "sourceId": "84337"
          },
          {
                "id": "55438",
                "title": "X-Factor (2020) #4",
                "digitalBookId": "55438",
                "marvelIssueId": "78749",
                "slug": "x-factor_2020_4",
                "drn": "drn:src:marvel:unison::prod:2126b64f-18de-4950-8510-aef6a54414ab",
                "sourceId": "78749"
          },
          {
                "id": "55573",
                "title": "Wolverine (2020) #6",
                "digitalBookId": "55573",
                "marvelIssueId": "78729",
                "slug": "wolverine_2020_6",
                "drn": "drn:src:marvel:unison::prod:4794fa10-293a-4078-97c0-fd50efb9403d",
                "sourceId": "78729"
          },
          {
                "id": "55575",
                "title": "X-Force (2019) #13",
                "digitalBookId": "55575",
                "marvelIssueId": "90131",
                "slug": "x-force_2019_13",
                "drn": "drn:src:marvel:unison::prod:d23e215f-0fd4-42ef-af25-e2bceef5e965",
                "sourceId": "90131"
          },
          {
                "id": "55559",
                "title": "Marauders (2019) #13",
                "digitalBookId": "55559",
                "marvelIssueId": "90081",
                "slug": "marauders_2019_13",
                "drn": "drn:src:marvel:unison::prod:8e3ca126-0bde-4f5a-8c78-65fe43919d0d",
                "sourceId": "90081"
          },
          {
                "id": "55554",
                "title": "Hellions (2020) #5",
                "digitalBookId": "55554",
                "marvelIssueId": "85944",
                "slug": "hellions_2020_5",
                "drn": "drn:src:marvel:unison::prod:2a9fb767-481d-44ca-89a4-828aac51a01e",
                "sourceId": "85944"
          },
          {
                "id": "55560",
                "title": "New Mutants (2019) #13",
                "digitalBookId": "55560",
                "marvelIssueId": "90449",
                "slug": "new_mutants_2019_13",
                "drn": "drn:src:marvel:unison::prod:27793715-ae6c-46e1-852f-77c6ccb75d54",
                "sourceId": "90449"
          },
          {
                "id": "55546",
                "title": "Cable (2020) #5",
                "digitalBookId": "55546",
                "marvelIssueId": "78657",
                "slug": "cable_2020_5",
                "drn": "drn:src:marvel:unison::prod:42e3a9a8-9836-4b66-bab6-caacb195c749",
                "sourceId": "78657"
          },
          {
                "id": "55550",
                "title": "Excalibur (2019) #13",
                "digitalBookId": "55550",
                "marvelIssueId": "84381",
                "slug": "excalibur_2019_13",
                "drn": "drn:src:marvel:unison::prod:33d53134-9260-4db1-b3ca-92979cdff81c",
                "sourceId": "84381"
          },
          {
                "id": "55576",
                "title": "X-Men (2019) #13",
                "digitalBookId": "55576",
                "marvelIssueId": "84427",
                "slug": "x-men_2019_13",
                "drn": "drn:src:marvel:unison::prod:85507bcf-df95-40a6-ad78-adc80df140ae",
                "sourceId": "84427"
          },
          {
                "id": "55574",
                "title": "X of Swords: Stasis (2020) #1",
                "digitalBookId": "55574",
                "marvelIssueId": "84338",
                "slug": "x_of_swords_stasis_2020_1",
                "drn": "drn:src:marvel:unison::prod:c3d30622-35df-489a-9b92-e2c31daca9da",
                "sourceId": "84338"
          },
          {
                "id": "55717",
                "title": "X-Men (2019) #14",
                "digitalBookId": "55717",
                "marvelIssueId": "84428",
                "slug": "x-men_2019_14",
                "drn": "drn:src:marvel:unison::prod:14efe3d8-a7a9-4ae6-9777-fcd511a8c648",
                "sourceId": "84428"
          },
          {
                "id": "55695",
                "title": "Marauders (2019) #14",
                "digitalBookId": "55695",
                "marvelIssueId": "90082",
                "slug": "marauders_2019_14",
                "drn": "drn:src:marvel:unison::prod:0dfdea56-728c-48a1-a8a0-e5e98515d653",
                "sourceId": "90082"
          },
          {
                "id": "55696",
                "title": "Marauders (2019) #15",
                "digitalBookId": "55696",
                "marvelIssueId": "90083",
                "slug": "marauders_2019_15",
                "drn": "drn:src:marvel:unison::prod:e4f8cff1-7b5d-4508-a4c4-6ebc844912ab",
                "sourceId": "90083"
          },
          {
                "id": "55685",
                "title": "Excalibur (2019) #14",
                "digitalBookId": "55685",
                "marvelIssueId": "84382",
                "slug": "excalibur_2019_14",
                "drn": "drn:src:marvel:unison::prod:c9c5ac19-564e-491c-8d63-12de8130a45e",
                "sourceId": "84382"
          },
          {
                "id": "55713",
                "title": "Wolverine (2020) #7",
                "digitalBookId": "55713",
                "marvelIssueId": "78730",
                "slug": "wolverine_2020_7",
                "drn": "drn:src:marvel:unison::prod:05e73c3e-404f-4b50-8bfb-d1a6dfaaf3ef",
                "sourceId": "78730"
          },
          {
                "id": "55716",
                "title": "X-Force (2019) #14",
                "digitalBookId": "55716",
                "marvelIssueId": "90132",
                "slug": "x-force_2019_14",
                "drn": "drn:src:marvel:unison::prod:5cc8be83-1576-40a9-8ee1-72cd9551c747",
                "sourceId": "90132"
          },
          {
                "id": "55690",
                "title": "Hellions (2020) #6",
                "digitalBookId": "55690",
                "marvelIssueId": "85945",
                "slug": "hellions_2020_6",
                "drn": "drn:src:marvel:unison::prod:abcd9ad3-cb50-4b27-a18b-e2753aa0e244",
                "sourceId": "85945"
          },
          {
                "id": "55680",
                "title": "Cable (2020) #6",
                "digitalBookId": "55680",
                "marvelIssueId": "78658",
                "slug": "cable_2020_6",
                "drn": "drn:src:marvel:unison::prod:2e385c87-0e4e-4f76-8715-444da49b6d6f",
                "sourceId": "78658"
          },
          {
                "id": "55718",
                "title": "X-Men (2019) #15",
                "digitalBookId": "55718",
                "marvelIssueId": "84429",
                "slug": "x-men_2019_15",
                "drn": "drn:src:marvel:unison::prod:e4462ff2-8b1f-4e2f-945e-39a811e134a5",
                "sourceId": "84429"
          },
          {
                "id": "55686",
                "title": "Excalibur (2019) #15",
                "digitalBookId": "55686",
                "marvelIssueId": "84383",
                "slug": "excalibur_2019_15",
                "drn": "drn:src:marvel:unison::prod:c485f6da-61bc-451a-b546-36abce5c173b",
                "sourceId": "84383"
          },
          {
                "id": "55715",
                "title": "X of Swords: Destruction (2020) #1",
                "digitalBookId": "55715",
                "marvelIssueId": "84339",
                "slug": "x_of_swords_destruction_2020_1",
                "drn": "drn:src:marvel:unison::prod:f7cb27e8-114b-49c5-9f79-ac20799fce5c",
                "sourceId": "84339"
          },
          {
                "id": "55551",
                "title": "Fantastic Four (2018) #25",
                "digitalBookId": "55551",
                "marvelIssueId": "77325",
                "slug": "fantastic_four_2018_25",
                "drn": "drn:src:marvel:unison::prod:4535dc23-9168-484e-9b0d-b0adff1704a1",
                "sourceId": "77325"
          },
          {
                "id": "55687",
                "title": "Fantastic Four (2018) #26",
                "digitalBookId": "55687",
                "marvelIssueId": "77326",
                "slug": "fantastic_four_2018_26",
                "drn": "drn:src:marvel:unison::prod:5b3170c6-7f5d-44a0-8645-71ab43c520df",
                "sourceId": "77326"
          }
    ],
  },
];

export function getStoryline(slug: string): Storyline | undefined {
  return STORYLINES.find((s) => s.slug === slug);
}
